### ISSUE TITLE
base64 image corrupted after upload to s3

### ISSUE THREAD

**Issue by eldyvoon** [RiptideElements/s3fs#55]
```
router.post('/image', multipartMiddleware , function(req, res) {
   var file_name = req.body.name;
   var data = req.body.data;

   return s3fsImpl.writeFile(file_name , data , 'base64').then(function (err) { 
        res.status(200).end();
    });
});
```
What's wrong in my code above? There's no error in my terminal, I have the file in my s3 but it's corrupted when I download it.

**Comment by DavidTPate** [comment]
I'm not sure exactly where the issue lies, so I have a few things for you to try. To give some background I already use this module to save, retrieve, etc. file uploads and other items to and from S3 without issue.

What's the actual value of `req.body.data`? I'm guessing it is something like 

```
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAYAAACt...
```

But with different values. If this is the case, you already have the encoding in the file, so you could just remove the `base64` part of your call to `s3fsImpl.writeFile(...)` and it should work as expected.

**Comment by DavidTPate** [comment]
Closing this as I expect it's a code problem as pointed out in my previous answer. If you are still having an issue feel free to respond @eldyvoon
